name: Sync Fork with OpenCTI

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Pull latest OpenCTI updates
        run: |
          git config --global user.email "szymon.kowalczyk@zf.com"
          git config --global user.name "szymon.kowalczyk"
          git remote add upstream https://github.com/OpenCTI-Platform/docker.git || true
          git fetch upstream main
          git checkout main
          git merge upstream/main --allow-unrelated-histories -m "Syncing OpenCTI updates"
          git push origin main
