name: Sync Fork with OpenCTI

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"

      - name: Add Upstream and Fetch Latest Updates
        run: |
          git remote remove upstream || true  # Ensure no duplicate remotes
          git remote add upstream https://github.com/OpenCTI-Platform/docker.git || true
          git fetch upstream master

      - name: Merge OpenCTI Updates into Fork
        run: |
          git checkout master
          git merge --allow-unrelated-histories -X theirs upstream/master -m "Syncing OpenCTI updates"

      - name: Push Updates to Your Fork
        run: |
          git push --force origin master
